[pytest]
python_files = test_*.py
python_classes = Test*
python_functions = test_*

testpaths = tests

markers =
    smoke: Smoke Tests
    regression: Regression Tests
    sanity: Sanity Tests

addopts = -v